/** Customer help library content. Every article says what is available today; anything not built is labelled Planned or Unsupported. Keep in step with docs/build-progress.md. */
export const HELP_VERSION = '2026-10-04'
export type Availability = 'available' | 'read-only' | 'planned' | 'unsupported'
export interface Article { id: string; section: string; title: string; summary: string; status: Availability; body: string[]; steps?: string[]; link?: { to: string; label: string } }

export const SECTIONS = ['Getting started', 'Plans and allowances', 'Loading your data', 'Planning rosters', 'Attendance and the kiosk', 'The employee app', 'Connections', 'Reports', 'Administration and support', 'Help and releases'] as const

export const ARTICLES: Article[] = [
  { id: 'first-setup', section: 'Getting started', title: 'Set up your organisation with guided setup', status: 'available', summary: 'One path from an empty organisation to a first roster; it remembers where you stopped.',
    body: ['Guided setup walks through: your site, your people, how long work takes, workload, optional labour rates, how people clock in, and your first roster. Steps tick themselves off from your data, so you can leave and return on any device.', 'If a platform administrator at Ensemble Solutions created your organisation, you start from the same page. Nothing needs a developer or the database.'],
    steps: ['Open Guided setup (the "Continue setup" button on the Overview, or /setup).', 'Add your first site: its ID, name and time zone. The time zone cannot be changed later because it would move your history.', 'Upload your people, work standards and workload using the templates.', 'Pick how people clock in, then generate a draft roster.'], link: { to: '/setup', label: 'Open guided setup' } },
  { id: 'two-routes', section: 'Getting started', title: 'The two ways an organisation is created', status: 'available', summary: 'Platform-assisted today; self-service sign-up is planned.',
    body: ['Platform-assisted (available): Ensemble Solutions creates your organisation, records your plan, and gives your first administrator a one-time invitation link. Tempo does not send emails yet, so the link is passed to you directly.', 'Self-service sign-up with email verification and card payment is planned. It is not available.'] },
  { id: 'roles', section: 'Getting started', title: 'Roles and what each can do', status: 'available', summary: 'Supervisors, planners, operations managers, tenant administrators and others.',
    body: ['Access comes from your role and your site grants. Planners build and edit rosters; operations managers approve and publish and approve timesheets; supervisors run the day (attendance list, corrections); tenant administrators configure sites, rules, devices and users; analysts and executives read.', 'A person who prepares a roster or a correction cannot approve their own: a second person decides. Platform staff are not part of your organisation and see nothing of it unless you are given a support session (see Support access).'] },

  { id: 'plans', section: 'Plans and allowances', title: 'Your plan, sites and worker allowance', status: 'read-only', summary: 'What the plan card in Administration shows and what it does not do.',
    body: ['Administration shows your plan, the number of sites you may have, and your active-worker count against your allowance band (up to 250, 251–500, 501–1,000, over 1,000).', 'Active workers means people marked active in Tempo today, counted once across all sites, including agency and labour-hire; inactive people are not counted.', 'Going over your allowance shows a warning. It never blocks work, never stops anyone clocking in, and nothing is charged automatically. Adding a site beyond your licensed number is refused with a message to contact us.', 'Plan prices and the feature matrix are indicative until Ensemble Solutions approves them. Card billing (Stripe) is planned and not connected: today arrangements are recorded by Ensemble Solutions.'], link: { to: '/admin', label: 'Open Administration' } },

  { id: 'csv-import', section: 'Loading your data', title: 'Load data from a spreadsheet', status: 'available', summary: 'Download a template, upload your own file, map columns, check, apply.',
    body: ['You can load sites, customers, staff, availability and leave, labour rates, work standards, forecasts, workload totals and workload events.', 'Your own column names are fine: Tempo suggests a mapping and you confirm it. Nothing changes until you press Apply, and every upload is checked first.'],
    steps: ['Data → Upload. Choose what you are loading and download its template.', 'Upload your file and confirm the column mapping (it can be saved for next time).', 'Read the preview: how many rows are new, changed, unchanged or rejected.', 'Apply. Workload, forecast and availability batches can be undone from the History tab.'], link: { to: '/data?tab=upload', label: 'Open Data' } },
  { id: 'import-errors', section: 'Loading your data', title: 'Fixing rejected rows', status: 'available', summary: 'Every rejected row says why, in plain words.',
    body: ['Rejected rows are listed with the reason (for example an unknown site, a time that does not exist because of a daylight-saving change, or a mixed unit). Download the rejected rows as a CSV, fix them and upload again.', 'You can apply only the accepted rows if you choose to; otherwise the batch is held. Re-uploading a corrected file never duplicates people or workload.', 'Staff, work-standard, site, customer and rate uploads are corrected by uploading a fixed file. Availability, forecast, totals and events can be undone.'] },
  { id: 'forecast-source', section: 'Loading your data', title: 'Choosing the forecast, and work standards', status: 'available', summary: 'Tempo’s own forecast or one you supply, per site; labour seconds per unit are versioned.',
    body: ['Each site uses either Tempo’s generated forecast or the forecast you supplied. The screen shows which one a roster was built on, and if a supplied forecast has gaps Tempo says it fell back and where.', 'A revised forecast flags open draft rosters for review. It never rewrites a published roster.', 'Work standards (labour seconds per unit, per activity) turn workload into required hours. A changed standard closes the previous one on its start date, so history stays explainable.'] },
  { id: 'api-ingestion', section: 'Loading your data', title: 'Send data from your systems (API)', status: 'available', summary: 'Service credentials, idempotency, batches and errors. The full reference is in the API documentation.',
    body: ['Create a service credential in Data → API credentials. It can only import data, is limited to the sites you choose, is shown once, and can be rotated or revoked.', 'Send rows as JSON to POST /v1/imports/batches with an Idempotency-Key. A retry returns the original receipt. The receipt lists accepted and rejected rows and what applying would change.', 'Limits: 20,000 rows per request. Larger loads must be split; background processing of very large files is not built.'], link: { to: '/help/api', label: 'API documentation' } },

  { id: 'roster-flow', section: 'Planning rosters', title: 'Draft, edit, approve and publish a roster', status: 'available', summary: 'The four states and why an edit cancels an approval.',
    body: ['Generate a draft from the forecast. Edit shifts by clicking them or dragging between workers and days; the server re-checks every change. A draft moves to Awaiting approval when submitted, then Approved by a different person, then Published; Tempo then reconciles what is live.', 'Editing a submitted or approved roster cancels the approval and returns it to Draft. A published roster is changed by copying it to a new draft.', 'Hard conflicts (overlaps, rest breaks, leave, certifications, weekly maximum) stop submission and publication; the board shows which shift and why.'], link: { to: '/roster', label: 'Open the roster planner' } },
  { id: 'planning-rules', section: 'Planning rosters', title: 'Planning rules, shifts, availability and leave', status: 'available', summary: 'Limits and shift times your rosters follow.',
    body: ['Planning rules (administrators) set minimum rest, weekly maximum, standard shift length, overtime and consecutive days, and the shift definitions the generator uses. Saving creates a new dated version; earlier ones are kept.', 'Availability & leave (planners) records times a person cannot work. A shift over one is a hard conflict. Entries that came from another system are read-only here.', 'The generator plans against rest, shift length, overtime and consecutive days; the weekly maximum is checked when a roster is validated.'] },
  { id: 'demand-overrides', section: 'Planning rosters', title: 'Adjusting the forecast with a reason', status: 'available', summary: 'Overrides need a reason and an expiry, and large ones a second approver.',
    body: ['A demand override changes the forecast for chosen dates. The model’s own number is always kept, and forecast accuracy is measured on the model. Large changes need a second person to approve.'], link: { to: '/demand', label: 'Open Demand' } },

  { id: 'kiosk-setup', section: 'Attendance and the kiosk', title: 'Set up a kiosk', status: 'available', summary: 'Enrol a tablet and give workers badge numbers and PINs.',
    body: ['A kiosk is a tablet or browser opened at /kiosk. It shows only the clock screen: no menus and no manager pages.'],
    steps: ['Administration → Kiosk devices: create a device for a site and note the one-time code (valid 15 minutes).', 'Open /kiosk on the tablet, enter the code. The device stays enrolled to that site.', 'Attendance → Badges & PINs: set a PIN (4–8 digits) for each worker. The badge number is the worker number from your staff upload.', 'Disable a lost or retired device in Administration; it stops working immediately.'], link: { to: '/admin', label: 'Open Administration' } },
  { id: 'clocking', section: 'Attendance and the kiosk', title: 'Clocking in, breaks and clocking out', status: 'available', summary: 'What workers see and what Tempo records.',
    body: ['A worker enters badge number and PIN, sees their name masked, and chooses Clock in, Start break, End break or Clock out (only the choices that make sense are offered). The confirmation appears only after Tempo has stored the punch, with Tempo’s time. A repeat tap within the site’s window says “already recorded” and records nothing new.', 'If the kiosk cannot reach Tempo it says so and does not pretend to have recorded anything. The kiosk does not store punches for later (offline capture is planned, not built).', 'Original punches are never changed or deleted.'] },
  { id: 'location', section: 'Attendance and the kiosk', title: 'Site geofence and location checks', status: 'available', summary: 'Optional: record or require the kiosk’s position at each tap.',
    body: ['Under Attendance → Rules an administrator can set a geofence (a circle round the site) and choose Off, Record or Require. Record keeps the position and flags taps outside the fence; Require refuses them.', 'This is the kiosk device’s position at the moment of the tap, not the worker’s, and browser location can be wrong. It is not continuous tracking.'], link: { to: '/attendance?view=rules', label: 'Open Attendance rules' } },
  { id: 'attendance-day', section: 'Attendance and the kiosk', title: 'The supervisor’s daily list', status: 'available', summary: 'Late, no-show, still clocked in, missing clock-out, not rostered, long days.',
    body: ['Attendance → Today lists, for one local day, who needs attention. “Late” and “missing clock-out” use the thresholds in Attendance → Rules (defaults are labelled as defaults). Tempo never closes a missing clock-out for you: you request a correction and a second person approves it.'], link: { to: '/attendance', label: 'Open Attendance' } },
  { id: 'timesheets', section: 'Attendance and the kiosk', title: 'Corrections, approval, reopening and the payroll file', status: 'available', summary: 'Worked, break and payable hours; revisions; exporting approved timesheets.',
    body: ['Worked is first to last punch; break is recorded break time; payable is worked less unpaid breaks, rounded as the site’s rules say, and is shown only once a timesheet is approved.', 'A correction is a separate request with a reason; someone else approves or rejects it. A missing shift can be added the same way. An approved timesheet changes only by being reopened with a reason, which records a revision and removes it from payroll exports until approved again.', 'The payroll CSV contains approved timesheets only and says how many it left out. It gives hours, not pay: Tempo does not interpret awards or loadings. The column layout is Tempo’s own.'] },
  { id: 'outage', section: 'Attendance and the kiosk', title: 'When the kiosk or network is down', status: 'available', summary: 'Supervisor route during an outage.',
    body: ['Workers are told the kiosk cannot clock them. A supervisor records their time afterwards with Add a missing timesheet (Attendance → Timesheets), which a second person approves. A locked PIN is unlocked or reset under Badges & PINs.'] },

  { id: 'employee-app', section: 'The employee app', title: 'Bring employees onto the Tempo app', status: 'available', summary: 'Invite people, what they see, and how to remove access.',
    body: ['The Tempo app (iPhone and Android) lets each employee see their published shifts and roster changes, answer shift offers, ask for leave, mark times they cannot work, see their clockings, and choose their notifications. They see only their own record. Draft rosters are never visible to them: a shift appears only when its roster is published.', 'Status: the app is built and tested, but it is not in the App Store or Google Play yet. Testers install it through TestFlight and Google Play internal testing, which need your developer accounts (see the mobile handover notes).'],
    steps: ['Attendance → Badges & PINs: choose Invite beside the person (they must be active).', 'Give the one-time link to the employee privately. Tempo does not email it. It works once and expires.', 'They open it on their phone, choose their own username and password, and sign in.', 'To remove access, choose Remove: their phone is signed out immediately and notifications stop.'], link: { to: '/attendance?view=badges', label: 'Open Badges & PINs' } },
  { id: 'offers', section: 'The employee app', title: 'Offer an extra shift', status: 'available', summary: 'Send an open shift to people on the app; the first to accept holds it until you confirm.',
    body: ['Shift offers: pick people who have joined the app, set the role, zone, times, break and instructions, and send. Each person answers on their phone. The first acceptance holds the shift; you confirm it onto the roster after a conflict check (overlap, rest time, leave). You can choose to confirm automatically when nothing conflicts.', 'If you change a shift after someone accepted it: before you confirmed, the acceptance is cleared and they are asked again. After you confirmed, the shift is updated and they must confirm the new details; it stays on their roster, flagged, until they do, and if they decline it is cancelled and you are alerted. Cancelling a confirmed offer removes the shift and tells them.'], link: { to: '/offers', label: 'Open Shift offers' } },
  { id: 'leave-requests', section: 'The employee app', title: 'Decide leave requests', status: 'available', summary: 'Approve or decline leave sent from the app.',
    body: ['Leave requests from the app wait for a decision. The screen shows how many rostered shifts fall in the requested days. Approving records the days as leave, which becomes a hard conflict for rostering; it does not remove shifts already rostered, so reassign them. Declining needs a reason. The employee is told either way and can cancel future leave themselves.'], link: { to: '/requests', label: 'Open Leave requests' } },
  { id: 'mobile-notifications', section: 'The employee app', title: 'Push notifications and text messages', status: 'available', summary: 'What is sent, what lock screens show, and what the delivery numbers mean.',
    body: ['Employees can be told when a roster is published, a shift changes or is cancelled, they get an offer, a reminder is due, or a request is decided. Lock-screen text is always generic (for example “Your roster has changed”); times, places and names appear only inside the app after sign-in. Each person chooses which kinds they get and how long before a shift to be reminded.', 'Administration → Mobile notifications shows three different numbers: accepted by the push provider (not proof of arrival), provider receipts (the provider says it handed the message to Apple or Google), and acknowledged by the phone (the app reported receiving it). If no push provider is configured, nothing is sent and the screen says so.', 'Text messages are optional, off by default, urgent changes only, for people who opted in with a number, within a monthly limit you set, and only when no push was accepted. No text provider is connected yet.'], link: { to: '/admin', label: 'Open Administration' } },
  { id: 'kiosk-app', section: 'The employee app', title: 'Tablet kiosk mode (iPad and Android tablets)', status: 'available', summary: 'Enrol a tablet, how workers clock, and how a manager leaves kiosk mode.',
    body: ['The Tempo app can run a shared tablet as a kiosk. A manager creates the device in Administration → Kiosk devices and gives a one-time code; entering it in the app on the tablet makes that tablet the kiosk for that company and site. Workers identify with their number and PIN, or by scanning a QR code shown in their own Tempo app (the code changes every minute and works once). They can clock in, start and end breaks, and clock out. The result screen only says success after Tempo has recorded it; if the connection is lost it says NOT recorded. It returns to the start screen by itself and clears everything about the person.', 'Leaving kiosk mode needs a manager’s sign-in on the tablet (a manager for that company and site; administrators also need their authenticator code). Managers can disable a device at any time in Administration; the tablet then stops working at once.', 'The app locks itself to the kiosk screen, but that is not operating-system lockdown. To stop staff leaving the app, set up iOS Guided Access (or Single App Mode through device management) or Android screen pinning (or a managed kiosk policy). See the kiosk setup notes.'] },
  { id: 'connections', section: 'Connections', title: 'Connecting Deputy or another workforce system', status: 'planned', summary: 'Not available yet: no live connection has been verified.',
    body: ['Connection setup screens and read-only groundwork exist, but no connection to Deputy or any other workforce system has been verified against a real account, so Tempo does not claim one is live. Until then use CSV or API loading, or Tempo’s own attendance.', 'When connections are verified, each site will have an explicit source of truth for workers, rosters and attendance so two systems never record the same clock. Publishing rosters out to another system is a separate, later capability.'] },
  { id: 'overlay', section: 'Connections', title: 'Sites run by another system (overlay)', status: 'read-only', summary: 'Hand a published roster over by file.',
    body: ['For an overlay site, publishing creates a hand-over file for the other system. Someone loads it there and records that they did. Tempo labels this as the operator’s statement, never as confirmed by the other system.'] },

  { id: 'metrics', section: 'Reports', title: 'What the report numbers mean', status: 'available', summary: 'Estimates versus confirmed; what is withheld.',
    body: ['Attended hours and estimated cost are estimates until timesheets are approved; payable hours and confirmed cost are confirmed. A figure with missing inputs (for example no rate) is shown as unavailable, never as zero.', 'Forecast error is measured on the model’s own forecast, not on manual overrides. Each day links to that day’s attendance list. Reports export to CSV for people with export permission.'], link: { to: '/reports', label: 'Open Reports' } },

  { id: 'users', section: 'Administration and support', title: 'People, access and the audit log', status: 'available', summary: 'Invite users, grant sites, review activity.',
    body: ['Administrators invite people, give them roles and site access, and can lock or unlock accounts. Administrators need two-step verification. The Audit log shows who did what and when for your organisation.'], link: { to: '/audit', label: 'Open the audit log' } },
  { id: 'support-access', section: 'Administration and support', title: 'How Tempo support can see your organisation', status: 'available', summary: 'Time-boxed, reasoned, read-only, audited.',
    body: ['Ensemble Solutions staff have no standing access to your data. To help with a problem they need a support grant: a recorded reason, chosen sites, a time limit of at most 8 hours, and for diagnostics a read-only view of counts and states (no names or personal data). It ends on its own or when ended early, and every view is recorded under the operator’s own name.'] },

  { id: 'api', section: 'Help and releases', title: 'API documentation', status: 'available', summary: 'Interactive reference and downloadable OpenAPI schema for the data API.',
    body: ['The data API reference lists the supported ingestion endpoints with authentication, idempotency, limits, time rules, correction semantics and sample payloads for every data class. Trying requests needs a service credential; no secrets are shown.'] },
  { id: 'problems', section: 'Help and releases', title: 'Common problems', status: 'available', summary: 'Quick answers.',
    body: ['“I can’t add a site”: your plan’s site limit has been reached, or you lack the configure permission.', '“Publish is disabled”: the roster has a hard conflict, or has not been approved by a different person.', '“A worker can’t clock in”: their PIN may be locked (Badges & PINs → Unlock), they may already be clocked in, or location is required and the kiosk cannot share it.', '“Payroll CSV is missing someone”: their timesheet is not approved yet; the file header says how many were left out.', '“Cost shows unavailable”: add labour rates in Data.'] },
  { id: 'releases', section: 'Help and releases', title: 'Release notes', status: 'available', summary: `Help version ${HELP_VERSION}.`,
    body: ['4 Oct 2026: employee app foundation (built and tested; not yet in the app stores), shift offers, leave requests, mobile notifications, tablet kiosk mode in the app.', '3 Oct 2026: platform operator console; support sessions; guided setup; help library and API documentation.', '2 Oct 2026: internal attendance with breaks, site rules, daily list, corrections, payroll file, geofence and location; planning rules, shifts, availability and leave; sites, customers, availability and rates import; plans and allowances.', '1 Oct 2026: guided data loading by spreadsheet and API.'] },
  { id: 'contact', section: 'Help and releases', title: 'Getting support', status: 'available', summary: 'Who to contact.',
    body: ['Contact your Ensemble Solutions representative. Include the page you were on, the time, and anything shown in a red banner. A dedicated support address and service levels have not been published yet.'] },
]
