import { api } from './client'
import type { Attendance, AvailabilityEntry, InboxItem, LeaveRequest, LoginResult, NotificationPrefs, Offer, Profile, Shift, ShiftChange } from './types'

export const login = (username: string, password: string) => api<LoginResult>('/mobile/auth/login', { method: 'POST', body: { username, password }, auth: false })
export const loginMfa = (challenge: string, code: string) => api<LoginResult>('/mobile/auth/mfa', { method: 'POST', body: { challenge, code }, auth: false })
export const logout = () => api('/mobile/auth/logout', { method: 'POST', body: {} })
export const inviteInfo = (token: string) => api<{ purpose: string; expires_at: string; password_rules: { min_length: number } }>(`/auth/invite/${encodeURIComponent(token)}`, { auth: false })
export const acceptInvite = (token: string, username: string, password: string) => api<{ status: string; username: string }>('/auth/accept-invite', { method: 'POST', body: { token, username, password }, auth: false })

export const getProfile = () => api<Profile>('/me/profile')
export const getShifts = (start?: string, end?: string) => api<{ as_of: string; timezone: string; shifts: Shift[] }>(`/me/shifts${start || end ? `?${new URLSearchParams({ ...(start ? { start } : {}), ...(end ? { end } : {}) })}` : ''}`)
export const getShift = (id: string) => api<Shift>(`/me/shifts/${id}`)
export const getChanges = () => api<{ unseen: number; changes: ShiftChange[] }>('/me/changes')
export const markChangesSeen = () => api('/me/changes/seen', { method: 'POST' })
export const getOffers = () => api<{ offers: Offer[] }>('/me/offers')
export const respondOffer = (id: string, action: 'accept' | 'decline', note?: string) => api<Offer>(`/me/offers/${id}/respond`, { method: 'POST', body: { action, note } })
export const getAvailability = () => api<{ entries: AvailabilityEntry[] }>('/me/availability')
export const addAvailability = (start_at: string, end_at: string) => api<AvailabilityEntry>('/me/availability', { method: 'POST', body: { start_at, end_at } })
export const removeAvailability = (id: string) => api(`/me/availability/${id}`, { method: 'DELETE' })
export const getLeave = () => api<{ requests: LeaveRequest[] }>('/me/leave')
export const requestLeave = (b: { kind: string; start_date: string; end_date: string; reason?: string }) => api<LeaveRequest>('/me/leave', { method: 'POST', body: b })
export const cancelLeave = (id: string) => api<LeaveRequest>(`/me/leave/${id}`, { method: 'DELETE' })
export const getAttendance = () => api<Attendance>('/me/attendance')
export const getPrefs = () => api<NotificationPrefs>('/me/notification-preferences')
export const putPrefs = (p: Partial<NotificationPrefs>) => api<NotificationPrefs>('/me/notification-preferences', { method: 'PUT', body: p })
export const getInbox = () => api<{ unread: number; items: InboxItem[] }>('/me/notifications')
export const readNotification = (id: string) => api(`/me/notifications/${id}/read`, { method: 'POST' })
export const ackNotification = (id: string, deviceId?: string) => api(`/me/notifications/${id}/ack`, { method: 'POST', body: { device_id: deviceId } })
export const registerPushDevice = (b: { token: string; platform: 'ios' | 'android'; app_version: string; label?: string }) => api<{ id: string }>('/me/push-devices', { method: 'POST', body: b })
export const removePushDevice = (id: string) => api(`/me/push-devices/${id}`, { method: 'DELETE' })
export const kioskQr = () => api<{ token: string; expires_at: string; ttl_seconds: number }>('/me/kiosk-qr', { method: 'POST' })
