export const landing = {
  nav: {
    links: [
      ['How it works', '#how'],
      ['AI engine', '#engine'],
      ['Integrations', '#integrations'],
      ['Pricing', '#pricing'],
      ['Resources', '#resources'],
    ],
    signIn: 'Sign in',
    cta: 'Start free trial',
  },
  hero: {
    eyebrow: 'AI labour platform for warehousing & 3PL',
    h1: 'Every shift, perfectly in tempo.',
    lead: 'Forecast demand, build the cheapest compliant roster, clock your people in and publish — all in one platform. Tempo cuts labour cost per unit without cutting corners on coverage.',
    primaryCta: 'Start your free trial',
    secondaryCta: 'See how it works',
    trust: ['14-day trial', 'No credit card', 'Live on your first site in a week'],
    mock: {
      label: 'NAMED ROSTER · MELBOURNE DC · WK 41',
      title: 'Proposed roster ready for approval',
      heatmap: {
        days: ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN'],
        rows: [
          ['Early', 'gggaggg'],
          ['Day', 'ggggrga'],
          ['Night', 'gaggggg'],
        ],
        legend: { g: 'Covered', a: 'Tight', r: 'At risk' },
      },
      baseline: 'A$184,200',
      proposed: 'A$163,900',
      delta: '−11.0%',
      confidence: 'Confidence 0.91 · high · 2 drivers',
      action: 'Approve & publish',
    },
  },
  stats: {
    note: 'Illustrative figures from modelled pilot scenarios. Your results depend on site, volume and workforce mix.',
    items: [
      ['−11%', 'Labour cost per unit shipped'],
      ['98.6%', 'Shift coverage at peak'],
      ['6 hrs', 'Saved per planner, every week'],
      ['< 5 min', 'From forecast to published roster'],
    ],
  },
  how: {
    eyebrow: 'HOW IT WORKS',
    h2: 'From the clock-in to the published roster. One loop.',
    lead: 'Tempo is a complete labour platform. Time & attendance, forecasting, rostering and approvals run on one data model, so every decision uses live data.',
    steps: [
      ['01', 'green', 'Capture', 'Kiosk clock-ins, rosters, leave and WMS backlog all flow into one live record of your workforce.'],
      ['02', 'green', 'Forecast', 'Predict volume by site, day and shift, then turn it into the exact labour hours you need.'],
      ['03', 'amber', 'Optimise', 'Solve for the cheapest roster that meets award rules, skills, certifications and fatigue limits.'],
      ['04', 'red', 'Act', 'Review the change, approve it and publish in one click. Tempo reconciles it once it lands.'],
    ],
  },
  engine: {
    eyebrow: 'THE AI ENGINE',
    h2: 'Ten optimisation models. One labour plan.',
    lead: "This isn't one generic AI model. Tempo uses a separate model for each labour decision: forecasting, mixed-integer programming, constraint programming and Monte Carlo simulation. Each model reports its confidence and what drove the result.",
    link: 'Try every model free →',
    models: [
      ['01', 'FORECAST', 'Demand forecast', 'Volume by site, day and shift.'],
      ['02', 'MILP', 'Labour requirement', 'Hours and headcount from forecast volume.'],
      ['03', 'MILP', 'Workforce mix', 'Best mix of permanent, casual and agency staff.'],
      ['04', 'CP-SAT', 'Named roster', 'Who works when, within every rule.'],
      ['05', 'MIN-COST FLOW', 'Intraday reallocation', 'Moves people to where the backlog is building.'],
      ['06', 'MILP', 'Training coverage', 'Keeps skills and certifications ahead of demand.'],
      ['07', 'MILP', 'Leave & RDO', 'Approves leave without breaking coverage.'],
      ['08', 'MILP', 'Team composition', 'Balanced crews by skill and experience.'],
      ['09', 'MILP', '3PL margin', 'Labour cost-to-serve by customer and contract.'],
      ['10', 'MONTE CARLO', 'Scenario planning', 'Stress-tests peak, absence and volume risk.'],
    ],
  },
  explain: {
    eyebrow: 'EXPLAINABLE BY DESIGN',
    h2: 'See exactly why. Approve it. Done.',
    lead: "Each recommendation shows the baseline, the proposal and the difference, plus the drivers behind it and any data that's missing. Nothing goes live without a person signing it off. Each change is validated, approved, written back and reconciled, with an audit trail at every step.",
    bullets: [
      ['green', 'Two-step approval with impact summary before execution'],
      ['amber', 'Role-based permissions: planners plan, managers approve'],
      ['red', 'Kill switch and one-click rollback to the last published roster'],
    ],
    drivers: [
      'Thursday inbound up 18% vs 6-week average. Two extra pickers moved from Night to Day.',
      'Casual agency hours reduced 140h by using 3 permanent staff with untapped availability.',
    ],
    missing: 'Forklift licence expiry for 2 workers not yet supplied.',
  },
  kiosk: {
    eyebrow: 'KIOSK & ATTENDANCE',
    h2: 'Clock-in that keeps your roster honest.',
    lead: 'Workers clock in with a PIN or NFC tag on a shared kiosk. No app to install. Geofencing confirms people are on site. Unrostered clock-ins show up as exceptions straight away, so supervisors can cover gaps before the shift falls behind.',
    features: [
      ['PIN & NFC', 'Works on any shared tablet'],
      ['GPS geofence', 'Per-site boundaries'],
      ['Exceptions first', 'Unmatched shifts flagged'],
    ],
  },
  integrations: {
    eyebrow: 'INTEGRATIONS',
    h2: 'Runs on its own. Works with what you have.',
    lead: 'Tempo can be your whole labour platform. If you already run UKG or Deputy, Tempo can sit on top of it instead. Either way, it reads live backlog from your WMS.',
    items: [
      ['Tempo Standalone', 'Built-in clock-in, rostering and publishing'],
      ['UKG Pro WFM', 'Use Tempo on top of UKG Pro WFM'],
      ['UKG Ready', 'Use Tempo on top of UKG Ready'],
      ['Deputy', 'Sync shifts, timesheets and leave'],
      ['WMS backlog', 'Live work-in-progress for intraday moves'],
      ['REST API', 'Every model and action, fully documented'],
    ],
  },
  security: {
    eyebrow: 'SECURITY',
    h2: 'Your labour data stays yours.',
    lead: 'Built for multi-site operators and 3PLs that handle data for several customers at once.',
    items: [
      ['Tenant isolation', 'Each customer’s data is kept separate at the database level, for every site and every query.'],
      ['Fine-grained permissions', 'Separate rights to plan, approve and configure. Margin data is restricted to finance.'],
      ['Full audit trail', 'Every run, recommendation and approval is logged and kept under your retention policy.'],
      ['Controlled support access', 'Our engineers can only access your data with a time-limited grant you approve.'],
    ],
  },
  pricing: {
    plans: [
      ['starter', 'Starter', 'For a single site replacing spreadsheets and paper timesheets.', ['Kiosk clock-in (PIN & NFC)', 'Demand forecast & named roster', 'One-click publish', 'Up to 150 workers'], 'Start free trial', false, ''],
      ['growth', 'Growth', 'For multi-site operators who need to optimise every shift.', ['All 10 optimisation models', 'Intraday reallocation from WMS', 'UKG & Deputy integrations', 'Approval workflows & audit'], 'Start free trial', true, 'Most popular'],
      ['enterprise', 'Enterprise', 'For 3PL networks with customer-level cost-to-serve and strict security needs.', ['3PL margin & scenario planning', 'Labour-hire provider portal', 'SSO & custom data retention', 'Dedicated success team'], 'Talk to sales', false, ''],
    ],
  },
  faq: [
    ['What is Tempo?', 'Tempo is an AI labour platform built for warehouses and 3PL operators. It brings time & attendance, demand forecasting, roster optimisation and approvals together, so you staff to real demand at the lowest cost while meeting your rules.'],
    ['Do I need UKG, Kronos or Deputy to use Tempo?', 'No. Tempo works on its own, with kiosk clock-in, rostering and publishing built in. If you already use UKG Pro WFM, UKG Ready or Deputy, Tempo can sit on top of it and send approved rosters back to it.'],
    ['How does AI rostering work in Tempo?', 'Tempo forecasts demand from your WMS backlog and attendance history. It then works out how many people you need, the right mix of permanent and casual staff, and who should work which shift. Each recommendation shows its confidence and the drivers behind it.'],
    ['Can I trust the recommendations?', 'Every recommendation shows the current roster, the proposed one, the difference and any data that was missing. Nothing goes live until a manager with approval rights signs it off. Every change can be rolled back.'],
    ['How long does it take to go live?', 'Most sites run their first optimised roster within a week. Use self-service onboarding to connect your systems, or let our team set it up for you.'],
    ['Do workers need an app to clock in?', 'No. Workers clock in on a shared kiosk with a PIN or NFC tag. Geofencing for each site is optional.'],
    ['How is Tempo priced?', 'Tempo is priced per active worker per month, billed monthly or annually. Every plan starts with a 14-day free trial, and no credit card is needed.'],
  ],
  resources: [
    ['GUIDE · 8 MIN', 'The 3PL operator’s guide to labour cost-to-serve'],
    ['PRODUCT · 5 MIN', 'Why explainable AI is the only AI planners will approve'],
    ['PLAYBOOK · 10 MIN', 'Forecasting peak: a playbook for warehouse GMs'],
  ],
  footer: {
    columns: [
      ['Product', ['Rostering', 'Time & attendance', 'Forecasting', 'Pricing']],
      ['Solutions', ['3PL', 'Warehousing', 'UKG & Kronos users', 'Deputy users']],
      ['Resources', ['Journal', 'Guides', 'API docs', 'Security']],
      ['Company', ['About', 'Careers', 'Contact', 'Partners']],
    ],
  },
} as const
