"""baseline schema

Revision ID: 6cc03e2823d8
Revises: 
Create Date: 2026-09-10 21:09:29.479966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cc03e2823d8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_request',
    sa.Column('action_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('recommendation_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('target', sa.JSON(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('expected_source_version', sa.String(), nullable=True),
    sa.Column('payload_hash', sa.String(), nullable=False),
    sa.Column('action_token_hash', sa.String(), nullable=False),
    sa.Column('approver_id', sa.String(), nullable=True),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_index(op.f('ix_action_request_recommendation_id'), 'action_request', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_action_request_site_id'), 'action_request', ['site_id'], unique=False)
    op.create_index(op.f('ix_action_request_tenant_id'), 'action_request', ['tenant_id'], unique=False)
    op.create_table('activity_role_zone_map',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('activity', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('zone', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_role_zone_map_tenant_id'), 'activity_role_zone_map', ['tenant_id'], unique=False)
    op.create_table('audit_record',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('actor_user_id', sa.String(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('request_name', sa.String(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('evidence_ref', sa.String(), nullable=True),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_record_tenant_id'), 'audit_record', ['tenant_id'], unique=False)
    op.create_table('connector_checkpoint',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('connection_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('watermark', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'connection_id', 'entity_type')
    )
    op.create_table('demand_bucket',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('activity', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('interval_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demand_bucket_tenant_id'), 'demand_bucket', ['tenant_id'], unique=False)
    op.create_table('event_record',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_event_record_event_type'), 'event_record', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_record_tenant_id'), 'event_record', ['tenant_id'], unique=False)
    op.create_table('ingestion_dead_letter',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('connection_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('quality_status', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('raw_envelope', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_dead_letter_tenant_id'), 'ingestion_dead_letter', ['tenant_id'], unique=False)
    op.create_table('kiosk_device',
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('site_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('credential_reference', sa.String(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config_version', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_index(op.f('ix_kiosk_device_tenant_id'), 'kiosk_device', ['tenant_id'], unique=False)
    op.create_table('labour_cost_rule',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('labour_type', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('rate', sa.String(), nullable=False),
    sa.Column('overtime_multiplier', sa.String(), nullable=True),
    sa.Column('surcharge', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labour_cost_rule_tenant_id'), 'labour_cost_rule', ['tenant_id'], unique=False)
    op.create_table('labour_provider',
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('provider_id')
    )
    op.create_index(op.f('ix_labour_provider_tenant_id'), 'labour_provider', ['tenant_id'], unique=False)
    op.create_table('maestro_connection',
    sa.Column('connection_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('connection_id')
    )
    op.create_index(op.f('ix_maestro_connection_tenant_id'), 'maestro_connection', ['tenant_id'], unique=False)
    op.create_table('optimisation_policy',
    sa.Column('policy_version', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('jurisdiction', sa.String(), nullable=True),
    sa.Column('constraints', sa.JSON(), nullable=False),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('tolerances', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('policy_version')
    )
    op.create_index(op.f('ix_optimisation_policy_tenant_id'), 'optimisation_policy', ['tenant_id'], unique=False)
    op.create_table('optimisation_run',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('run_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('request', sa.JSON(), nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('policy_version', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.JSON(), nullable=True),
    sa.Column('lineage', sa.JSON(), nullable=True),
    sa.Column('supersedes_run_id', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_optimisation_run_idempotency_key'), 'optimisation_run', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_optimisation_run_tenant_id'), 'optimisation_run', ['tenant_id'], unique=False)
    op.create_table('recommendation',
    sa.Column('recommendation_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('body', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    op.create_index(op.f('ix_recommendation_run_id'), 'recommendation', ['run_id'], unique=False)
    op.create_index(op.f('ix_recommendation_tenant_id'), 'recommendation', ['tenant_id'], unique=False)
    op.create_table('security_audit_event',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('reason_code', sa.String(), nullable=True),
    sa.Column('session_or_grant_ref', sa.String(), nullable=True),
    sa.Column('correlation_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_security_audit_event_actor_id'), 'security_audit_event', ['actor_id'], unique=False)
    op.create_index(op.f('ix_security_audit_event_correlation_id'), 'security_audit_event', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_security_audit_event_tenant_id'), 'security_audit_event', ['tenant_id'], unique=False)
    op.create_table('sell_rate_contract',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('activity', sa.String(), nullable=False),
    sa.Column('rate', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('sla_penalty', sa.String(), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sell_rate_contract_tenant_id'), 'sell_rate_contract', ['tenant_id'], unique=False)
    op.create_table('service_client',
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('credential_prefix', sa.String(), nullable=False),
    sa.Column('credential_hash', sa.String(), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('site_ids', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_service_client_credential_prefix'), 'service_client', ['credential_prefix'], unique=False)
    op.create_index(op.f('ix_service_client_tenant_id'), 'service_client', ['tenant_id'], unique=False)
    op.create_table('site_geofence',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('radius_meters', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'site_id')
    )
    op.create_table('source_version_watermark',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('connection_id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'connection_id', 'site_id', 'resource_type')
    )
    op.create_table('tempo_user',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('external_subject', sa.String(), nullable=False),
    sa.Column('account_status', sa.String(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('mfa_policy_ref', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_tempo_user_external_subject'), 'tempo_user', ['external_subject'], unique=True)
    op.create_table('tenant_scope',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'site_id')
    )
    op.create_table('work_standard',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('activity', sa.String(), nullable=False),
    sa.Column('complexity_segment', sa.String(), nullable=True),
    sa.Column('time_per_unit_seconds', sa.Float(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_standard_tenant_id'), 'work_standard', ['tenant_id'], unique=False)
    op.create_table('zone_backlog',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('zone', sa.String(), nullable=False),
    sa.Column('interval_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('backlog_units', sa.Float(), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('source_ref', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zone_backlog_source_ref'), 'zone_backlog', ['source_ref'], unique=False)
    op.create_index(op.f('ix_zone_backlog_tenant_id'), 'zone_backlog', ['tenant_id'], unique=False)
    op.create_table('optimisation_run_customer',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['optimisation_run.run_id'], ),
    sa.PrimaryKeyConstraint('run_id', 'customer_id')
    )
    op.create_index(op.f('ix_optimisation_run_customer_customer_id'), 'optimisation_run_customer', ['customer_id'], unique=False)
    op.create_index(op.f('ix_optimisation_run_customer_tenant_id'), 'optimisation_run_customer', ['tenant_id'], unique=False)
    op.create_table('optimisation_run_site',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['optimisation_run.run_id'], ),
    sa.PrimaryKeyConstraint('run_id', 'site_id')
    )
    op.create_index(op.f('ix_optimisation_run_site_site_id'), 'optimisation_run_site', ['site_id'], unique=False)
    op.create_index(op.f('ix_optimisation_run_site_tenant_id'), 'optimisation_run_site', ['tenant_id'], unique=False)
    op.create_table('privileged_support_grant',
    sa.Column('grant_id', sa.String(), nullable=False),
    sa.Column('operator_user_id', sa.String(), nullable=False),
    sa.Column('login_session_id', sa.String(), nullable=True),
    sa.Column('target_tenant_id', sa.String(), nullable=False),
    sa.Column('site_ids', sa.JSON(), nullable=False),
    sa.Column('action_categories', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('approver_user_id', sa.String(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('terminated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approver_user_id'], ['tempo_user.user_id'], ),
    sa.ForeignKeyConstraint(['operator_user_id'], ['tempo_user.user_id'], ),
    sa.PrimaryKeyConstraint('grant_id')
    )
    op.create_index(op.f('ix_privileged_support_grant_operator_user_id'), 'privileged_support_grant', ['operator_user_id'], unique=False)
    op.create_index(op.f('ix_privileged_support_grant_target_tenant_id'), 'privileged_support_grant', ['target_tenant_id'], unique=False)
    op.create_table('tenant_membership',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invitation_source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tempo_user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'tenant_id')
    )
    op.create_table('user_customer_grant',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tempo_user.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tenant_id', 'customer_id', name='uq_user_customer_grant')
    )
    op.create_index(op.f('ix_user_customer_grant_tenant_id'), 'user_customer_grant', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_user_customer_grant_user_id'), 'user_customer_grant', ['user_id'], unique=False)
    op.create_table('user_provider_grant',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['labour_provider.provider_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tempo_user.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tenant_id', 'provider_id', name='uq_user_provider_grant')
    )
    op.create_index(op.f('ix_user_provider_grant_tenant_id'), 'user_provider_grant', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_user_provider_grant_user_id'), 'user_provider_grant', ['user_id'], unique=False)
    op.create_table('user_role_assignment',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tempo_user.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tenant_id', 'role', name='uq_user_role_assignment')
    )
    op.create_index(op.f('ix_user_role_assignment_tenant_id'), 'user_role_assignment', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_user_role_assignment_user_id'), 'user_role_assignment', ['user_id'], unique=False)
    op.create_table('user_session',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('session_family_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('refresh_token_digest', sa.String(), nullable=False),
    sa.Column('csrf_digest', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('replaced_by', sa.String(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('device_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tempo_user.user_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_user_session_session_family_id'), 'user_session', ['session_family_id'], unique=False)
    op.create_index(op.f('ix_user_session_user_id'), 'user_session', ['user_id'], unique=False)
    op.create_table('user_site_grant',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tempo_user.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tenant_id', 'site_id', name='uq_user_site_grant')
    )
    op.create_index(op.f('ix_user_site_grant_tenant_id'), 'user_site_grant', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_user_site_grant_user_id'), 'user_site_grant', ['user_id'], unique=False)
    op.create_table('worker',
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('employment_type', sa.String(), nullable=False),
    sa.Column('home_site', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('source_ref', sa.String(), nullable=True),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['labour_provider.provider_id'], ),
    sa.PrimaryKeyConstraint('worker_id')
    )
    op.create_index(op.f('ix_worker_provider_id'), 'worker', ['provider_id'], unique=False)
    op.create_index(op.f('ix_worker_source_ref'), 'worker', ['source_ref'], unique=False)
    op.create_index(op.f('ix_worker_tenant_id'), 'worker', ['tenant_id'], unique=False)
    op.create_table('attendance_session',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('breaks_minutes', sa.Float(), nullable=False),
    sa.Column('approval', sa.String(), nullable=False),
    sa.Column('pay_code', sa.String(), nullable=True),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('source_ref', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.worker_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_session_source_ref'), 'attendance_session', ['source_ref'], unique=False)
    op.create_index(op.f('ix_attendance_session_tenant_id'), 'attendance_session', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_attendance_session_worker_id'), 'attendance_session', ['worker_id'], unique=False)
    op.create_table('availability',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('interval_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interval_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('preference', sa.Float(), nullable=True),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('source_ref', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.worker_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_source_ref'), 'availability', ['source_ref'], unique=False)
    op.create_index(op.f('ix_availability_tenant_id'), 'availability', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_availability_worker_id'), 'availability', ['worker_id'], unique=False)
    op.create_table('shift_assignment',
    sa.Column('shift_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('zone', sa.String(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('source_ref', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.worker_id'], ),
    sa.PrimaryKeyConstraint('shift_id')
    )
    op.create_index(op.f('ix_shift_assignment_source_ref'), 'shift_assignment', ['source_ref'], unique=False)
    op.create_index(op.f('ix_shift_assignment_tenant_id'), 'shift_assignment', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_shift_assignment_worker_id'), 'shift_assignment', ['worker_id'], unique=False)
    op.create_table('skill_certification',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('skill_code', sa.String(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('evidence_ref', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.worker_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_certification_tenant_id'), 'skill_certification', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_skill_certification_worker_id'), 'skill_certification', ['worker_id'], unique=False)
    op.create_table('worker_credential',
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('pin_hash', sa.String(), nullable=True),
    sa.Column('nfc_tag_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.worker_id'], ),
    sa.PrimaryKeyConstraint('worker_id'),
    sa.UniqueConstraint('tenant_id', 'pin_hash', name='uq_worker_credential_tenant_pin')
    )
    op.create_index(op.f('ix_worker_credential_nfc_tag_id'), 'worker_credential', ['nfc_tag_id'], unique=False)
    op.create_index(op.f('ix_worker_credential_tenant_id'), 'worker_credential', ['tenant_id'], unique=False)
    op.create_table('worker_performance_profile',
    sa.Column('worker_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('cost_per_hour', sa.String(), nullable=True),
    sa.Column('productivity_index', sa.Float(), nullable=True),
    sa.Column('quality_index', sa.Float(), nullable=True),
    sa.Column('reliability_index', sa.Float(), nullable=True),
    sa.Column('is_mentor', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['worker.worker_id'], ),
    sa.PrimaryKeyConstraint('worker_id')
    )
    op.create_index(op.f('ix_worker_performance_profile_tenant_id'), 'worker_performance_profile', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_performance_profile_tenant_id'), table_name='worker_performance_profile')
    op.drop_table('worker_performance_profile')
    op.drop_index(op.f('ix_worker_credential_tenant_id'), table_name='worker_credential')
    op.drop_index(op.f('ix_worker_credential_nfc_tag_id'), table_name='worker_credential')
    op.drop_table('worker_credential')
    op.drop_index(op.f('ix_skill_certification_worker_id'), table_name='skill_certification')
    op.drop_index(op.f('ix_skill_certification_tenant_id'), table_name='skill_certification')
    op.drop_table('skill_certification')
    op.drop_index(op.f('ix_shift_assignment_worker_id'), table_name='shift_assignment')
    op.drop_index(op.f('ix_shift_assignment_tenant_id'), table_name='shift_assignment')
    op.drop_index(op.f('ix_shift_assignment_source_ref'), table_name='shift_assignment')
    op.drop_table('shift_assignment')
    op.drop_index(op.f('ix_availability_worker_id'), table_name='availability')
    op.drop_index(op.f('ix_availability_tenant_id'), table_name='availability')
    op.drop_index(op.f('ix_availability_source_ref'), table_name='availability')
    op.drop_table('availability')
    op.drop_index(op.f('ix_attendance_session_worker_id'), table_name='attendance_session')
    op.drop_index(op.f('ix_attendance_session_tenant_id'), table_name='attendance_session')
    op.drop_index(op.f('ix_attendance_session_source_ref'), table_name='attendance_session')
    op.drop_table('attendance_session')
    op.drop_index(op.f('ix_worker_tenant_id'), table_name='worker')
    op.drop_index(op.f('ix_worker_source_ref'), table_name='worker')
    op.drop_index(op.f('ix_worker_provider_id'), table_name='worker')
    op.drop_table('worker')
    op.drop_index(op.f('ix_user_site_grant_user_id'), table_name='user_site_grant')
    op.drop_index(op.f('ix_user_site_grant_tenant_id'), table_name='user_site_grant')
    op.drop_table('user_site_grant')
    op.drop_index(op.f('ix_user_session_user_id'), table_name='user_session')
    op.drop_index(op.f('ix_user_session_session_family_id'), table_name='user_session')
    op.drop_table('user_session')
    op.drop_index(op.f('ix_user_role_assignment_user_id'), table_name='user_role_assignment')
    op.drop_index(op.f('ix_user_role_assignment_tenant_id'), table_name='user_role_assignment')
    op.drop_table('user_role_assignment')
    op.drop_index(op.f('ix_user_provider_grant_user_id'), table_name='user_provider_grant')
    op.drop_index(op.f('ix_user_provider_grant_tenant_id'), table_name='user_provider_grant')
    op.drop_table('user_provider_grant')
    op.drop_index(op.f('ix_user_customer_grant_user_id'), table_name='user_customer_grant')
    op.drop_index(op.f('ix_user_customer_grant_tenant_id'), table_name='user_customer_grant')
    op.drop_table('user_customer_grant')
    op.drop_table('tenant_membership')
    op.drop_index(op.f('ix_privileged_support_grant_target_tenant_id'), table_name='privileged_support_grant')
    op.drop_index(op.f('ix_privileged_support_grant_operator_user_id'), table_name='privileged_support_grant')
    op.drop_table('privileged_support_grant')
    op.drop_index(op.f('ix_optimisation_run_site_tenant_id'), table_name='optimisation_run_site')
    op.drop_index(op.f('ix_optimisation_run_site_site_id'), table_name='optimisation_run_site')
    op.drop_table('optimisation_run_site')
    op.drop_index(op.f('ix_optimisation_run_customer_tenant_id'), table_name='optimisation_run_customer')
    op.drop_index(op.f('ix_optimisation_run_customer_customer_id'), table_name='optimisation_run_customer')
    op.drop_table('optimisation_run_customer')
    op.drop_index(op.f('ix_zone_backlog_tenant_id'), table_name='zone_backlog')
    op.drop_index(op.f('ix_zone_backlog_source_ref'), table_name='zone_backlog')
    op.drop_table('zone_backlog')
    op.drop_index(op.f('ix_work_standard_tenant_id'), table_name='work_standard')
    op.drop_table('work_standard')
    op.drop_table('tenant_scope')
    op.drop_index(op.f('ix_tempo_user_external_subject'), table_name='tempo_user')
    op.drop_table('tempo_user')
    op.drop_table('source_version_watermark')
    op.drop_table('site_geofence')
    op.drop_index(op.f('ix_service_client_tenant_id'), table_name='service_client')
    op.drop_index(op.f('ix_service_client_credential_prefix'), table_name='service_client')
    op.drop_table('service_client')
    op.drop_index(op.f('ix_sell_rate_contract_tenant_id'), table_name='sell_rate_contract')
    op.drop_table('sell_rate_contract')
    op.drop_index(op.f('ix_security_audit_event_tenant_id'), table_name='security_audit_event')
    op.drop_index(op.f('ix_security_audit_event_correlation_id'), table_name='security_audit_event')
    op.drop_index(op.f('ix_security_audit_event_actor_id'), table_name='security_audit_event')
    op.drop_table('security_audit_event')
    op.drop_index(op.f('ix_recommendation_tenant_id'), table_name='recommendation')
    op.drop_index(op.f('ix_recommendation_run_id'), table_name='recommendation')
    op.drop_table('recommendation')
    op.drop_index(op.f('ix_optimisation_run_tenant_id'), table_name='optimisation_run')
    op.drop_index(op.f('ix_optimisation_run_idempotency_key'), table_name='optimisation_run')
    op.drop_table('optimisation_run')
    op.drop_index(op.f('ix_optimisation_policy_tenant_id'), table_name='optimisation_policy')
    op.drop_table('optimisation_policy')
    op.drop_index(op.f('ix_maestro_connection_tenant_id'), table_name='maestro_connection')
    op.drop_table('maestro_connection')
    op.drop_index(op.f('ix_labour_provider_tenant_id'), table_name='labour_provider')
    op.drop_table('labour_provider')
    op.drop_index(op.f('ix_labour_cost_rule_tenant_id'), table_name='labour_cost_rule')
    op.drop_table('labour_cost_rule')
    op.drop_index(op.f('ix_kiosk_device_tenant_id'), table_name='kiosk_device')
    op.drop_table('kiosk_device')
    op.drop_index(op.f('ix_ingestion_dead_letter_tenant_id'), table_name='ingestion_dead_letter')
    op.drop_table('ingestion_dead_letter')
    op.drop_index(op.f('ix_event_record_tenant_id'), table_name='event_record')
    op.drop_index(op.f('ix_event_record_event_type'), table_name='event_record')
    op.drop_table('event_record')
    op.drop_index(op.f('ix_demand_bucket_tenant_id'), table_name='demand_bucket')
    op.drop_table('demand_bucket')
    op.drop_table('connector_checkpoint')
    op.drop_index(op.f('ix_audit_record_tenant_id'), table_name='audit_record')
    op.drop_table('audit_record')
    op.drop_index(op.f('ix_activity_role_zone_map_tenant_id'), table_name='activity_role_zone_map')
    op.drop_table('activity_role_zone_map')
    op.drop_index(op.f('ix_action_request_tenant_id'), table_name='action_request')
    op.drop_index(op.f('ix_action_request_site_id'), table_name='action_request')
    op.drop_index(op.f('ix_action_request_recommendation_id'), table_name='action_request')
    op.drop_table('action_request')
    # ### end Alembic commands ###
