"""int03 connector credential reference

Revision ID: 881bb55c3809
Revises: e65468392c02
Create Date: 2026-09-10 21:27:43.950876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '881bb55c3809'
down_revision: Union[str, Sequence[str], None] = 'e65468392c02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connector_credential_reference',
    sa.Column('connection_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('vault_secret_reference', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['maestro_connection.connection_id'], ),
    sa.PrimaryKeyConstraint('connection_id')
    )
    op.create_index(op.f('ix_connector_credential_reference_tenant_id'), 'connector_credential_reference', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connector_credential_reference_tenant_id'), table_name='connector_credential_reference')
    op.drop_table('connector_credential_reference')
    # ### end Alembic commands ###
