"""dat06 snapshot manifest and linkage

Revision ID: e65468392c02
Revises: 6cc03e2823d8
Create Date: 2026-09-10 21:16:56.356137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e65468392c02'
down_revision: Union[str, Sequence[str], None] = '6cc03e2823d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('optimisation_snapshot',
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('policy_version', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('data_versions', sa.JSON(), nullable=False),
    sa.Column('extraction_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['optimisation_run.run_id'], ),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_index(op.f('ix_optimisation_snapshot_run_id'), 'optimisation_snapshot', ['run_id'], unique=True)
    op.create_index(op.f('ix_optimisation_snapshot_tenant_id'), 'optimisation_snapshot', ['tenant_id'], unique=False)
    op.add_column('action_request', sa.Column('snapshot_id', sa.String(), nullable=True))
    op.add_column('recommendation', sa.Column('snapshot_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendation', 'snapshot_id')
    op.drop_column('action_request', 'snapshot_id')
    op.drop_index(op.f('ix_optimisation_snapshot_tenant_id'), table_name='optimisation_snapshot')
    op.drop_index(op.f('ix_optimisation_snapshot_run_id'), table_name='optimisation_snapshot')
    op.drop_table('optimisation_snapshot')
    # ### end Alembic commands ###
